export const AGREGAR_RESERVA = "AGREGAR_RESERVA";
export const SELECCIONAR_RESERVA = "SELECCIONAR_RESERVA";

export const SUMAR_SALA_UNO = "SUMAR_SALA_UNO"
export const SUMAR_SALA_DOS = "SUMAR_SALA_DOS"
export const SUMAR_SALA_TRES = "SUMAR_SALA_TRES"
